### ISSUE TITLE
Check parameters

### ISSUE THREAD

**Issue by audreyrepetti** [carlossantosgarcia/PnP_Lantern#1]
Hi Carlos, 

I am checking for details in the code after we received the review of the paper. I am trying to find the value of the \delta parameter in the paper which I think corresponds to https://github.com/carlossantosgarcia/PnP_Lantern/blob/1677338615a2b9c955b4bd6503e6b026594e5d82/eval_models.py#L42 
However it cannot be equal to 50, so I guess there is a typo?
Can you also send me an email with your new email address, I cannot find it...

Thanks in advance

**Comment by carlossantosgarcia** [comment]
Hi Audrey, 

The \delta from the paper refers to the `epsilon` attribute from the `JacobianReg_l2` loss from `train/loss.py`. This value was set to 0.05, as shown in `data/ckpt/config.yaml` file. The epsilon you refer to is the one called also \epsilon in the paper, controlling the L2 norm of \w. 

I'll send the email with our adresses.

Best, Carlos
